services:
  web:
    build:
      context: ./web
    ports:
      - "5009:5004"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    build:
      context: ./redis
    restart: always

  test:
    build:
      context: ./web
    command: pytest tests
    volumes:
      - .:/app
    depends_on:
      - web
    restart: "no"
