version: "3.8"

services:
  web:
    build:
      context: ./web
    ports:
      - "5004:5004"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  redis:
    build:
      context: ./redis
    restart: always
    # Optional Redis healthcheck
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  test:
    build:
      context: ./web
    command: pytest tests/
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - web
    restart: "no"
    tty: true
