FROM python:3.9-slim

WORKDIR /app

# Installing curl for healthcheck
RUN apt-get update && apt-get install -y curl && apt-get clean

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]
